# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Parameters.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 195)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Comp = QtWidgets.QRadioButton(self.centralwidget)
        self.Comp.setGeometry(QtCore.QRect(10, 30, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.Comp.setFont(font)
        self.Comp.setChecked(True)
        self.Comp.setObjectName("Comp")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.Comp)
        self.Human = QtWidgets.QRadioButton(self.centralwidget)
        self.Human.setGeometry(QtCore.QRect(10, 70, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.Human.setFont(font)
        self.Human.setChecked(False)
        self.Human.setObjectName("Human")
        self.buttonGroup_2.addButton(self.Human)
        self.X = QtWidgets.QRadioButton(self.centralwidget)
        self.X.setEnabled(True)
        self.X.setGeometry(QtCore.QRect(290, 40, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.X.setFont(font)
        self.X.setCheckable(True)
        self.X.setChecked(True)
        self.X.setObjectName("X")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.X)
        self.O = QtWidgets.QRadioButton(self.centralwidget)
        self.O.setEnabled(True)
        self.O.setGeometry(QtCore.QRect(290, 80, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.O.setFont(font)
        self.O.setCheckable(True)
        self.O.setChecked(False)
        self.O.setObjectName("O")
        self.buttonGroup.addButton(self.O)
        self.Start = QtWidgets.QPushButton(self.centralwidget)
        self.Start.setGeometry(QtCore.QRect(140, 130, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.Start.setFont(font)
        self.Start.setObjectName("Start")
        self.Cancel = QtWidgets.QPushButton(self.centralwidget)
        self.Cancel.setGeometry(QtCore.QRect(270, 130, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.Cancel.setFont(font)
        self.Cancel.setObjectName("Cancel")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 0, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.Race = QtWidgets.QLabel(self.centralwidget)
        self.Race.setGeometry(QtCore.QRect(230, 0, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Race.setFont(font)
        self.Race.setObjectName("Race")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setEnabled(False)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.Comp, self.Human)
        MainWindow.setTabOrder(self.Human, self.X)
        MainWindow.setTabOrder(self.X, self.O)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Новая игра"))
        self.Comp.setText(_translate("MainWindow", "С компьютером"))
        self.Human.setText(_translate("MainWindow", "С человеком"))
        self.X.setText(_translate("MainWindow", "X"))
        self.O.setText(_translate("MainWindow", "O"))
        self.Start.setText(_translate("MainWindow", "Начать"))
        self.Cancel.setText(_translate("MainWindow", "Отмена"))
        self.label.setText(_translate("MainWindow", " Режим игры"))
        self.Race.setText(_translate("MainWindow", "Кеми будете"))

